# typed: false
# frozen_string_literal: true

# Regenerate the package listings in the repository root.
#
#   brew ruby scripts/generate-docs.rb          # rewrite FORMULAE.md and CASKS.md
#   brew ruby scripts/generate-docs.rb -- --check  # fail if they are out of date
#
# Name, description and version are read from the package objects themselves,
# so the tables cannot drift from the .rb files.
#
# Known wrinkle, measured rather than assumed: table rows sit on adjacent
# lines, and git cannot auto-merge changes to adjacent lines. Two bump pull
# requests touching different packages therefore conflict on this file
# (`git merge-file` exits 1). Nothing here can fix that — a blank-line
# separated list merges cleanly, a table does not — so it is handled in CI
# instead: the merge workflow skips a conflicted pull request with a warning
# and nudges the bump workflow, which rebuilds every branch from the new main
# and force-pushes, clearing the conflict.
#
# The recorded date is the day a version was first written here, not the
# file's mtime and not its last commit date. mtime is meaningless after a fresh
# checkout, and a commit date would always lag by one bump because these tables
# are regenerated before the commit that carries them. Instead the previous
# table is read back and a date is only refreshed when the version changed,
# which also keeps regeneration idempotent.

require "cask/cask_loader"

module DocsGenerator
  extend Utils::Output::Mixin

  module_function

  TAP_NAME = "mihalych-pro/tap"

  Section = Struct.new(:file, :title, :heading, keyword_init: true)
  SECTIONS = {
    formula: Section.new(file: "FORMULAE.md", title: "Formulae", heading: "Formula"),
    cask:    Section.new(file: "CASKS.md", title: "Casks", heading: "Cask"),
  }.freeze

  GENERATED_NOTE = "<!-- Generated by scripts/generate-docs.rb. Run `task docs` to refresh. -->"

  Entry = Struct.new(:name, :description, :version, :link, keyword_init: true)

  def tap = Tap.fetch(TAP_NAME)

  # A cell must not break the table with a stray pipe or newline, and an empty
  # one must not collapse it.
  def cell(value)
    collapsed = value.to_s.gsub(/\s+/, " ").strip
    return "—" if collapsed.empty?

    collapsed.gsub("|", "\\|")
  end

  def entries_for(kind)
    files = (kind == :cask) ? tap.cask_files : tap.formula_files

    Homebrew.with_no_api_env do
      files.filter_map do |path|
        package = (kind == :cask) ? Cask::CaskLoader.load(path) : Formulary.factory(path)
        Entry.new(
          name:        (kind == :cask) ? package.token : package.name,
          description: package.desc,
          version:     package.version,
          # tap.path is the tap directory; the docs sit at its root.
          link:        path.relative_path_from(tap.path).to_s,
        )
      rescue Homebrew::UntrustedTapError
        onoe "#{path.basename(".rb")}: untrusted, left out of the listing"
        puts "  vouch for the tap once with: brew trust --tap #{TAP_NAME}"
        nil
      end
    end.sort_by(&:name)
  end

  ROW = /^\|\s*\[([^\]]+)\]\([^)]*\)\s*\|.*\|\s*(\S+)\s*\|\s*(\S+)\s*\|$/

  # name => [version, date], read back from a table written by an earlier run.
  def previous_dates(path)
    return {} unless path.exist?

    path.read.lines.each_with_object({}) do |raw, dates|
      match = ROW.match(raw.chomp)
      dates[match[1]] = [match[2], match[3]] if match
    end
  end

  def render(kind, today)
    section = SECTIONS.fetch(kind)
    path = tap.path/section.file
    previous = previous_dates(path)

    rows = entries_for(kind).map do |entry|
      known_version, known_date = previous[entry.name]
      date = (known_version == entry.version.to_s) ? known_date : today

      "| [#{entry.name}](#{entry.link}) | #{cell(entry.description)} | #{cell(entry.version)} | #{date} |"
    end

    body = if rows.empty?
      "None yet."
    else
      ["| #{section.heading} | Description | Version | Updated |",
       "| --- | --- | --- | --- |",
       *rows].join("\n")
    end

    [path, "# #{section.title}\n\n#{GENERATED_NOTE}\n\n#{body}\n"]
  end

  def main(argv)
    check_only = argv.include?("--check")
    today = Time.now.utc.strftime("%Y-%m-%d")
    stale = []

    SECTIONS.each_key do |kind|
      path, contents = render(kind, today)
      current = path.exist? ? path.read : nil

      if current == contents
        puts "#{path.basename}: up to date"
        next
      end

      if check_only
        stale << path.basename.to_s
        next
      end

      path.atomic_write(contents)
      puts "#{path.basename}: written"
    end

    return if stale.empty?

    odie "out of date: #{stale.join(", ")} — run `task docs`"
  end
end

DocsGenerator.main(ARGV)
