# typed: false
# frozen_string_literal: true

# Regenerate the package listings in the repository root.
#
#   brew ruby scripts/generate-docs.rb          # rewrite FORMULAE.md and CASKS.md
#   brew ruby scripts/generate-docs.rb -- --check  # fail if they are out of date
#
# Name, description and version are read from the package objects themselves,
# so the tables cannot drift from the .rb files.
#
# Known wrinkle, measured rather than assumed: table rows sit on adjacent
# lines, and git cannot auto-merge changes to adjacent lines. Two bump pull
# requests touching different packages therefore conflict on this file
# (`git merge-file` exits 1). Nothing here can fix that — a blank-line
# separated list merges cleanly, a table does not — so it is handled in CI
# instead: the merge workflow skips a conflicted pull request with a warning
# and nudges the bump workflow, which rebuilds every branch from the new main
# and force-pushes, clearing the conflict.
#
# The recorded date is the day a version was first written here, not the
# file's mtime and not its last commit date. mtime is meaningless after a fresh
# checkout, and a commit date would always lag by one bump because these tables
# are regenerated before the commit that carries them. Instead the previous
# table is read back and a date is only refreshed when the version changed,
# which also keeps regeneration idempotent.

require "cask/cask_loader"
require "utils/popen"

module DocsGenerator
  extend Utils::Output::Mixin

  module_function

  TAP_NAME = "mihalych-pro/tap"

  Section = Struct.new(:file, :title, :heading, keyword_init: true)
  SECTIONS = {
    formula: Section.new(file: "FORMULAE.md", title: "Formulae", heading: "Formula"),
    cask:    Section.new(file: "CASKS.md", title: "Casks", heading: "Cask"),
  }.freeze

  GENERATED_NOTE = "<!-- Generated by scripts/generate-docs.rb. Run `task docs` to refresh. -->"

  Entry = Struct.new(:name, :description, :platforms, :version, :link, keyword_init: true)

  PLATFORMS = [[:macos, :arm], [:macos, :intel], [:linux, :arm], [:linux, :intel]].freeze
  OS_LABELS = { macos: "macOS", linux: "Linux" }.freeze
  ARCH_LABELS = { arm: "arm64", intel: "x86_64" }.freeze

  def tap = Tap.fetch(TAP_NAME)

  # A cell must not break the table with a stray pipe or newline, and an empty
  # one must not collapse it.
  def cell(value)
    collapsed = value.to_s.gsub(/\s+/, " ").strip
    return "—" if collapsed.empty?

    collapsed.gsub("|", "\\|")
  end

  # Whether a package resolves on one simulated platform. Asking Homebrew is
  # what makes this trustworthy: reading the `on_*` blocks would miss
  # `depends_on arch:`, which a cask uses to rule out an architecture even
  # though the url for that OS loads perfectly well.
  def available?(kind, path, os, arch)
    Homebrew::SimulateSystem.with(os:, arch:) do
      Homebrew.with_no_api_env do
        if kind == :cask
          cask = Cask::CaskLoader.load(path)
          next false if cask.url.blank?
          next false unless (os == :macos) ? cask.supports_macos? : cask.supports_linux?

          required = cask.depends_on.arch&.filter_map { |entry| entry[:type] }
          required.blank? || required.include?(arch)
        else
          Formulary.factory(path).stable&.url.present?
        end
      end
    end
  rescue
    # With no url for the simulated platform Homebrew raises rather than
    # returning nil, and that is exactly the answer we want.
    false
  end

  def platforms_for(kind, path)
    supported = PLATFORMS.select { |os, arch| available?(kind, path, os, arch) }
    grouped = supported.group_by(&:first)

    labelled = OS_LABELS.filter_map do |os, os_label|
      arches = grouped[os]&.map { |(_, arch)| ARCH_LABELS.fetch(arch) }
      next if arches.blank?

      "#{os_label} (#{arches.join(", ")})"
    end
    labelled.join(", ")
  end

  # Packages git ignores are not in the repository, so listing them would
  # describe a file the reader cannot open — and CI, which never checks them
  # out, would strip those rows again on the next bump.
  def ignored(paths)
    return [] if paths.empty?

    Utils.popen_read("git", "-C", tap.path.to_s, "check-ignore", *paths.map(&:to_s))
         .lines.map { |line| Pathname(line.chomp) }
  end

  def entries_for(kind)
    files = (kind == :cask) ? tap.cask_files : tap.formula_files
    files -= ignored(files)

    Homebrew.with_no_api_env do
      files.filter_map do |path|
        package = (kind == :cask) ? Cask::CaskLoader.load(path) : Formulary.factory(path)
        Entry.new(
          name:        (kind == :cask) ? package.token : package.name,
          description: package.desc,
          platforms:   platforms_for(kind, path),
          version:     package.version,
          # tap.path is the tap directory; the docs sit at its root.
          link:        path.relative_path_from(tap.path).to_s,
        )
      rescue Homebrew::UntrustedTapError
        onoe "#{path.basename(".rb")}: untrusted, left out of the listing"
        puts "  vouch for the tap once with: brew trust --tap #{TAP_NAME}"
        nil
      end
    end.sort_by(&:name)
  end

  ROW = /^\|\s*\[([^\]]+)\]\([^)]*\)\s*\|.*\|\s*(\S+)\s*\|\s*(\S+)\s*\|$/

  # name => [version, date], read back from a table written by an earlier run.
  def previous_dates(path)
    return {} unless path.exist?

    path.read.lines.each_with_object({}) do |raw, dates|
      match = ROW.match(raw.chomp)
      dates[match[1]] = [match[2], match[3]] if match
    end
  end

  def render(kind, today)
    section = SECTIONS.fetch(kind)
    path = tap.path/section.file
    previous = previous_dates(path)

    rows = entries_for(kind).map do |entry|
      known_version, known_date = previous[entry.name]
      date = (known_version == entry.version.to_s) ? known_date : today

      "| [#{entry.name}](#{entry.link}) | #{cell(entry.description)} | " \
        "#{cell(entry.platforms)} | #{cell(entry.version)} | #{date} |"
    end

    body = if rows.empty?
      "None yet."
    else
      ["| #{section.heading} | Description | Platforms | Version | Updated |",
       "| --- | --- | --- | --- | --- |",
       *rows].join("\n")
    end

    [path, "# #{section.title}\n\n#{GENERATED_NOTE}\n\n#{body}\n"]
  end

  def main(argv)
    check_only = argv.include?("--check")
    today = Time.now.utc.strftime("%Y-%m-%d")
    stale = []

    SECTIONS.each_key do |kind|
      path, contents = render(kind, today)
      current = path.exist? ? path.read : nil

      if current == contents
        puts "#{path.basename}: up to date"
        next
      end

      if check_only
        stale << path.basename.to_s
        next
      end

      path.atomic_write(contents)
      puts "#{path.basename}: written"
    end

    return if stale.empty?

    odie "out of date: #{stale.join(", ")} — run `task docs`"
  end
end

DocsGenerator.main(ARGV)
